all:
	ilbm2raw -b -f ./1.iff 1.raw
	cp 1.raw ../../src/assets/banners/
	cp 1.raw.0 ../../src/assets/banners/
	cp 1.raw.1 ../../src/assets/banners/
	cp 1.raw.2 ../../src/assets/banners/

	ilbm2raw -b -f ./2.iff 2.raw
	cp 2.raw ../../src/assets/banners/
	cp 2.raw.0 ../../src/assets/banners/
	cp 2.raw.1 ../../src/assets/banners/
	cp 2.raw.2 ../../src/assets/banners/

	ilbm2raw -b -f ./3.iff 3.raw
	cp 3.raw ../../src/assets/banners/
	cp 3.raw.0 ../../src/assets/banners/
	cp 3.raw.1 ../../src/assets/banners/
	cp 3.raw.2 ../../src/assets/banners/

	ilbm2raw -b -f ./go.iff go.raw
	cp go.raw ../../src/assets/banners/
	cp go.raw ../../src/assets/banners/
	cp go.raw.0 ../../src/assets/banners/
	cp go.raw.1 ../../src/assets/banners/
	cp go.raw.2 ../../src/assets/banners/

	ilbm2raw -b -f ./acctostart.iff acctostart.raw
	cp acctostart.raw.0 ../../src/assets/banners/
	cp acctostart.raw.1 ../../src/assets/banners/
	cp acctostart.raw.2 ../../src/assets/banners/
