all:
	ilbm2raw -f -i ./cursor_left.iff ./cursor_left.raw
	cp ./cursor_left.raw ../../src/assets/cursors/cursor_left.spr

	ilbm2raw -f -i ./cursor_right.iff ./cursor_right.raw
	cp ./cursor_right.raw ../../src/assets/cursors/cursor_right.spr