all:
	rm -f ./car_0.raw
	ilbm2raw -i ./car_0.iff ./car_0.raw
	cp ./car_0.raw ../../src/assets/cars_small

	rm -f ./car_15.raw
	ilbm2raw  -i ./car_15.iff ./car_15.raw
	cp ./car_15.raw ../../src/assets/cars_small

	rm -f ./car_30.raw
	ilbm2raw  -i ./car_30.iff ./car_30.raw
	cp ./car_30.raw ../../src/assets/cars_small

	rm -f ./car_45.raw
	ilbm2raw  -i ./car_45.iff ./car_45.raw
	cp ./car_45.raw ../../src/assets/cars_small

	rm -f ./car_60.raw
	ilbm2raw  -i ./car_60.iff ./car_60.raw
	cp ./car_60.raw ../../src/assets/cars_small

	rm -f ./car_75.raw
	ilbm2raw  -i ./car_75.iff ./car_75.raw
	cp ./car_75.raw ../../src/assets/cars_small

	rm -f ./car_90.raw
	ilbm2raw  -i ./car_90.iff ./car_90.raw
	cp ./car_90.raw ../../src/assets/cars_small

	rm -f ./car_105.raw
	ilbm2raw  -i ./car_105.iff ./car_105.raw
	cp ./car_105.raw ../../src/assets/cars_small

	rm -f ./car_120.raw
	ilbm2raw  -i ./car_120.iff ./car_120.raw
	cp ./car_120.raw ../../src/assets/cars_small

	rm -f ./car_135.raw
	ilbm2raw  -i ./car_135.iff ./car_135.raw
	cp ./car_135.raw ../../src/assets/cars_small

	rm -f ./car_150.raw
	ilbm2raw  -i ./car_150.iff ./car_150.raw
	cp ./car_150.raw ../../src/assets/cars_small

	rm -f ./car_165.raw
	ilbm2raw  -i ./car_165.iff ./car_165.raw
	cp ./car_165.raw ../../src/assets/cars_small

	rm -f ./car_180.raw
	ilbm2raw  -i ./car_180.iff ./car_180.raw
	cp ./car_180.raw ../../src/assets/cars_small

	rm -f ./car_195.raw
	ilbm2raw  -i ./car_195.iff ./car_195.raw
	cp ./car_195.raw ../../src/assets/cars_small

	rm -f ./car_210.raw
	ilbm2raw  -i ./car_210.iff ./car_210.raw
	cp ./car_210.raw ../../src/assets/cars_small

	rm -f ./car_225.raw
	ilbm2raw  -i ./car_225.iff ./car_225.raw
	cp ./car_225.raw ../../src/assets/cars_small

	rm -f ./car_240.raw
	ilbm2raw  -i ./car_240.iff ./car_240.raw
	cp ./car_240.raw ../../src/assets/cars_small

	rm -f ./car_255.raw
	ilbm2raw  -i ./car_255.iff ./car_255.raw
	cp ./car_255.raw ../../src/assets/cars_small

	rm -f ./car_270.raw
	ilbm2raw  -i ./car_270.iff ./car_270.raw
	cp ./car_270.raw ../../src/assets/cars_small

	rm -f ./car_285.raw
	ilbm2raw  -i ./car_285.iff ./car_285.raw
	cp ./car_285.raw ../../src/assets/cars_small

	rm -f ./car_300.raw
	ilbm2raw  -i ./car_300.iff ./car_300.raw
	cp ./car_300.raw ../../src/assets/cars_small

	rm -f ./car_315.raw
	ilbm2raw  -i ./car_315.iff ./car_315.raw
	cp ./car_315.raw ../../src/assets/cars_small

	rm -f ./car_330.raw
	ilbm2raw  -i ./car_330.iff ./car_330.raw
	cp ./car_330.raw ../../src/assets/cars_small

	rm -f ./car_345.raw
	ilbm2raw  -i ./car_345.iff ./car_345.raw
	cp ./car_345.raw ../../src/assets/cars_small
