# taken from https://archive.org/download/car-engines

all:
	sox ferrari.wav -r 8000 -t s8 -D ../../src/assets/sounds/ferrari.raw8
	sox mclaren.wav -r 8000 -t s8 -D ../../src/assets/sounds/mclaren.raw8
	sox alfamarameo.wav -r 8000 -t s8 -D ../../src/assets/sounds/alfamarameo.raw8
